name: Compile Unlocked Namida

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Build Windows EXE
        run: flutter build windows --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Namida-Unlocked-APK
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Namida-Unlocked-Windows
          path: build/windows/x64/runner/Release/*
